### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JustGioox** [GZTimeWalker/GGOS#12]
Hello, i tried to install the ggOs, i clicked sistem thing and when i tried installing it, it does blue screen and when i try to go in recovery mode it says that i file is missing and the file is windows\system32\boot\winload.efi. please help.

**Comment by GZTimeWalker** [comment]
Sorry for that, but GGOS is only a OS course project and it cannot run on any physical machines.

Please check that your file system still exists and is in good health, and try to repair windows boot files and EFI partition. You may need some disk utils and tools like dism++.

This problem is not related to this project, so I'm going to close the issue.
